(define (make-account balance pwd)
  (define (withdraw amount)
    (if (>= balance amount)
      (begin (set! balance (- balance amount))
             balance
        )
      "Insufficient funds"))
  (define (deposit amount)
    (set! balance (+ balance amount))
    balance)
  (define (dispatch inputPwd m)
    (if (eq? pwd inputPwd)
      (cond ((eq? m 'withdraw) withdraw)
        ((eq? m 'deposit) deposit)
        (else (error "Unknown request - MAKE-ACCOUNT" m))
        )
      (error "Incorrect password")
      )
    )
  dispatch
  )

(define myAccount (make-account 100 'reallysafepassword))
((myAccount 'reallysafepassword 'withdraw) 40)
((myAccount 'reallysafepassword 'withdraw) 400)
((myAccount 'wrongpwd 'deposit) 50)
